server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audit_demo
    username: postgres
    password: julien
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
